apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "5"
    field.cattle.io/publicEndpoints: '[{"addresses":["192.168.10.150"],"port":30501,"protocol":"TCP","serviceName":"hotelreservaties-app:hotel-api-nodeport","allNodes":true}]'
  name: hotel-api
  namespace: hotelreservaties-app
  uid: f20c7e68-c67f-4001-9669-216e1134ecec
spec:
  replicas: 1
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-hotelreservaties-app-hotel-api
  template:
    metadata:
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-hotelreservaties-app-hotel-api
    spec:
      affinity: {}
      containers:
      - envFrom:
        - secretRef:
            name: db-connection-typeorm-secret
            optional: false
        image: ghcr.io/everaertalexander/hotel-reservatie-api
        imagePullPolicy: Always
        name: hotel-api
        ports:
        - containerPort: 3000
          name: 3000tcp30501
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      nodeName: everaert-alexander
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30