apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  name: mariadb
  namespace: hotelreservaties-app
  resourceVersion: "526707521"
  uid: 03eabcf3-677d-4505-ba1c-d5659cd98b57
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-hotelreservaties-app-mariadb
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-hotelreservaties-app-mariadb
    spec:
      affinity: {}
      containers:
      - envFrom:
        - secretRef:
            name: db-connection-secret
            optional: false
        image: mariadb:10.5.12
        imagePullPolicy: Always
        name: mariadb
        ports:
        - containerPort: 3306
          name: 3306tcp
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /mnt/data/hotelreservaties-app-db
          name: hotel-vol
      dnsPolicy: ClusterFirst
      nodeName: everaert-alexander
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: hotel-vol
        persistentVolumeClaim:
          claimName: hotelreservaties-app-pvc