name: Workflow

on:
  push:
    tags:
      - 'v*.*.*'
    
  workflow_dispatch:

jobs:
  Build:
    runs-on: self-hosted
    strategy:
      max-parallel: 1
    steps:
    - uses: actions/checkout@v2
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Test
      run: |
        echo $RELEASE_VERSION
        echo ${{ env.RELEASE_VERSION }}
    - name: Copy Google credentials
      run: echo $CREDENTIALS_FILE >> ./server/auth/application-credentials.json  
      shell: bash
      env:
        CREDENTIALS_FILE: ${{ secrets.gcp_credentials }}
    - name: Check google credentials
      run: cat ./server/auth/application-credentials.json
    - name: Build docker image
      run: docker build -t ghcr.io/everaertalexander/hotel-reservatie-api:$RELEASE_VERSION .
    - name: Push docker image
      run: docker push ghcr.io/everaertalexander/hotel-reservatie-api:$RELEASE_VERSION
    - name: Check kubernetes
      run: kubectl get pods --namespace hotelreservaties-app
    - name: Create or update K8 deployment
      run: kubectl apply -f ./k8/api-manifest.yaml
    - name: Update kubernetes image
      run: |
        kubectl set image deployment/hotel-api hotel-api=ghcr.io/everaertalexander/hotel-reservatie-api:$RELEASE_VERSION
    
