name: Workflow

on:
  push:
    branches: [ feature/github-actions ]
  pull_request:
    branches: [ feature/github-actions ]
    
  workflow_dispatch:

jobs:

  build:
    runs-on: everaert-alexander
    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: echo Add other actions to build,
           echo test, and deploy your project.
