name: Workflow

on:
  push:
    branches: [ feature/github-actions ]
  pull_request:
    branches: [ feature/github-actions ]
    
  workflow_dispatch:

jobs:

  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Copy google credentials
      run: cp ~/hotel-secrets/application-credentials.json ./server/auth/application-credentials.json
    - name: Check google credentials
      run: cat ./server/auth/application-credentials.json
